### ISSUE TITLE
Some questions about Nerofest.

### ISSUE THREAD

**Issue by consistentescape** [29988122/Fate-Grand-Order_Lua#218] opened 2019-08-23 16:43 UTC
I wanted to ask if anyone has tried using this script to automate Nerofest farming. If yes, how did you do it? Did you go for a guaranteed 3T or it can be facecarded?

**Comment by TryBane** [comment] 2019-08-23 22:03
Guaranteed 3T is by far the best option for any lotto farming event. It is guaranteed, and has the best return on investment for the cost of the subscription.

**Comment by consistentescape** [comment] 2019-08-27 13:40
Could you elaborate a bit on how you set it up? If possible, I would like to facecard it as well but I can't figure it out since I am using this for the first time.

**Comment by GleipnirFR** [comment] 2019-08-29 07:42
Note that you don't have to set absolutely every turn up if you plan of facecarding.
Here is an example : 
--AutoSkill
Enable_Autoskill = 1
Skill_Confirmation = 0
Skill_Command = "hi,#,0,#,abcdefghi456"

"hi,#" => With this, you would use your 3rd servant's 2nd and 3rd skill on the first turn (let's say a support Waver). The "#" represents the end of the round, so in this case the script would not use any other skill for the first round, and will simply select plain face cards until the end of the round.
"0,#" => With this, faceturning, plain and simple.
"abcdefghi456" => the script unleashes hell on the boss(es).
By playing with "#", you can plan each round instead of going too specific with each turn which could be boring to do, and less adaptative (if you are unlucky with your NP damage for instance, and some foe is still barely alive).

You have to adjust the settings to your setup, but it's quite simple to do (don't be afraid to try your own shenanigans while monitoring the script, so you can stop it if anything goes wrong and correct your setup accordingly).

**Comment by vit2657** [comment] 2019-08-29 08:32
I created a pull request with CE's for nerofest that I have added for myself: https://github.com/29988122/Fate-Grand-Order_Lua/pull/223

Good luck with lotto farming all

**Comment by TryBane** [comment] 2019-08-29 10:13
I confirmed the merge, good job and thanks!

**Comment by Kizuro** [comment] 2019-08-30 11:08
Is it possible to use auto_gift_exchange for exchanging the Spins? Whenever I use those script, it seems to be clicking Nero face instead of the 10 Spins icon below her.

**Comment by GleipnirFR** [comment] 2019-08-30 14:31
Yeah, I've got the same issue. Maybe that module was for previous Christmas lottery, and the UI is not exactly the same (not sure, since I started playing FGO after that) ?
I don't want to stop my script right now, since I've go a lot of apples to burn, but maybe tinkering with the offset might be enough ? Remember that we will be able to open boxes for a few days after the end of Nerofest, so you can worry about that later :)
But still, if anyone has some insight to share in order to correct this script, I think it would be helpful for a bunch of us :D

**Comment by forgehe** [comment] 2019-08-30 20:35
Can you try this script?
https://raw.githubusercontent.com/forgehe/Fate-Grand-Order_Lua/master/_auto_nero_lottery.lua
It just clicks on one space over and over again, which should activate the 10 roll until the petals are all used up.

**Comment by TryBane** [comment] 2019-08-31 02:06
I have the same issue on my device. I'll go through it soon to take a look. The benefit of the provided script we have is that it also performs box resets so I would like it to work as it should.

**Comment by TryBane** [comment] 2019-08-31 11:52
Alrighty, I have updated the gift exchange. It should work so long as you don't have a notch :D

**Comment by vit2657** [comment] 2019-08-31 13:26
@TryBane for the notch user I should just put extra x offset myself, right?

**Comment by TryBane** [comment] 2019-08-31 13:39
Yes, if you are aware of what the extra offset is, then just add that to the xOffset. The gift exchange script uses the old resolution solution. Not the one that is supposed to fix notch resolutions.

**Comment by GleipnirFR** [comment] 2019-09-02 06:55
@TryBane thanks for the script. I tried it with a bunch of boxes and it works flawlessly and with the new check for the full present box, it's perfect 🥇

**Comment by TryBane** [comment] 2019-09-02 06:56
Awesome. I'll close this thread as the initial question has also been answered

**Closed** 2019-09-02 06:56 UTC

**Comment by Kizuro** [comment] 2019-09-04 06:11
@TryBane Just want to ask, but how could I edit the script so that the auto gift exchange could work on my phone? Still got the previous problem of clicking above the 10 spins

**Comment by TryBane** [comment] 2019-09-04 06:16
Change this. Add a value to yOffset if it is clicking too high, or subtract if it is too low. For x, add a value if it is too far the left, subtract if it is too far to the right.

![](https://i.imgur.com/FKWVin4.jpg)

**Comment by Kizuro** [comment] 2019-09-04 06:24
Alright it works. Need to double both of the value so that it properly click on the right place. Though, looks like it doesnt reset the prize huh, just clicking

**Comment by TryBane** [comment] 2019-09-04 06:27
If it isn't resetting the prize, you'll have to do that to the yOffset itself rather than just that one instance.

Remove the change you made and place this right above it:

yOffset = yOffset * 2
