### ISSUE TITLE
Android version/Accessibility mode caused Support_SwipesPerUpdate stop working

### ISSUE THREAD

**Issue by Zaein** [29988122/Fate-Grand-Order_Lua#149] opened 2018-12-25 23:08 UTC
I followed the instructions, but was still unable to run the script. After browsing the forum, it seems to be an issue with using the latest android software I.E I can't run Daemon tools while outside of USB debugging mode. This is an issue since I can't run FGO while USB debugging tools are active.

I don't understand the purpose of the fastboot/adb stuff. Is this able to fix my issue? And would I need to use Magisk 18 too?

Sometimes I use Samsung SlideSync to connect my phone to my PC and then play FGO that way. Is there a method of just using the FGO lua script through my PC to play via the SlideSync link?

Thanks! The script looks really great and I want to give it a shot. I have manually farmed 100's of these Demon Pillars and am sick of it lol...

**Comment by l3ombyx** [comment] 2018-12-26 08:56
What version of Android are you running? If it's 8.0 and above it won't work. (At least I'm pretty sure. Don't quote me though since I'm pretty much a noob.) You can however use this script with an android emulator called Nox, which is what I'm currently using. It's pretty easy to set up: Copy the script to Nox (I suggest googling this), disable root (you can do this in setting via the cog wheel at the top), run the daemon bat file. (There's one in the folder that's specific to Nox. c:) and you should be good to go.

**Comment by Zaein** [comment] 2018-12-26 09:01
The problem I have with using an emulator is that would require me transferring my account off of my phone and onto my pc, correct? That seems like a rather large hassle since I play from my phone all the time.

**Comment by l3ombyx** [comment] 2018-12-26 09:06
That's correct, unfortunately. I'm not really sure of any other options. Hopefully someone more knowledgeable an has an alternate solution.

**Comment by Zaein** [comment] 2018-12-26 09:10
Do you happen to know if your account be transferred an infinite number of times or do they cap you out on it?

And yes, we can only hope that someone else will have the answer! I appreciate your help though! Using an emulator with Nox is a solution!

**Comment by TryBane** [comment] 2018-12-26 13:10
You can use Ankulua on android 8.0 and higher, but it is a bitch for multiple reasons. I personally recommend getting Nox working, and if you really want to play on your phone, set up remote desktop to connect from your phone to PC, but if you are adamant about getting it to work on your phone, I will first explain the downsides to doing so on Android 8.0 and higher.

Firstly, Daemon simply won't run on 8.0 and higher. In order to get everything to work right you have to use Media Projection. Not everything is rosy though, as it lags the game up a crap storm, and after a couple of hours will eventually soft-reboot your phone because of the hit on your phones' CPU.

Secondly, this will NOT harm your phone. So I don't want you to get the wrong idea about the first downside, it doesn't hurt, just an inconvenience.

Thirdly, will the most recent update to the script, it relies more heavily on screen capture, meaning if the phone lags, the screen might show an image but then lag before getting things ready to be pressed. What this can cause is some issues. IF you end up running into this, there is a fix, it just isn't in the script as of this moment. You have to create a new wait() time for 1 second, and replace the wait() that comes after decodeSkill() to 1 second instead of .3 seconds.

If you need help with this, I can create a branch for you to download yourself if necessary.

Now in order to get this to work, you need to get Ankulua version 8.1.1, the latest version. When you open Akulua, go into settings and make sure Media Projection is on and you are using Accessibility mode. These two things are what will allow you to use Ankulua WITHOUT Daemon. Follow the rest of the steps (ignore the ones that ask you to enter USB Debugging and such) and you should be good to go.

If all of this sounds like more than you want, then go with Nox. I don't know how to get it to work tbh, as I've tried and failed. I could probably figure it out but my phone is Android 7.0 so I am fine using it for now. If you need help getting it to work on Nox, then I'm sure others are completely willing to help you out.

**Comment by Zaein** [comment] 2018-12-26 22:43
Thank you for the tips TryBane. I am unable to try the Ankulua work around right now but should be able to in a few hours!

**Comment by TryBane** [comment] 2018-12-26 22:56
There is also apparently a workaround to get Daemon to work. [Here](http://ankulua.boards.net/thread/3/daemon-installation) is the link, just scroll down to where it mentions 8.0 Android devices and higher.

**Comment by Zaein** [comment] 2018-12-26 23:04
LOL will do man. 

I have killed 100's of Demon Pillars manually, it wont be the end of the world of you have to manually do things for a bit :p 
This is all coming from a guy that use to bot like crazy on Runescape (back in the day!)

**Comment by TryBane** [comment] 2018-12-26 23:09
I never had an issue with doing it manually. My issue is that i don't have time to do it manually. My issue is simply how much time I have. I usually do things manually if I can, but working 60 hours a week, plus taking care of my 93 year old grandma at home, and then also dealing with other obligations that require my attention over the week leaves me with very little time to enjoy this game. If I had to farm everything by hand, forget enjoying the story at all.

**Comment by 29988122** [comment] 2018-12-27 00:11
I'll add a way to quickly transfer accounts **WITHOUT** using bind codes in readme.md.
Soon^TM

You'll need to purchase Titanium backup, or able to bash chmod/chown files.
Root needed(temporary root or Magisk's enough).

**Comment by TryBane** [comment] 2018-12-27 02:35
Btw @29988122 had to update the release because of the bug that was present in the init() function where Autoskill List wasn't working properly.

**Comment by Zaein** [comment] 2018-12-27 02:55
TryBane, I am currently trying the method you proposed earlier. But I have one question, where do I place the first wait time? 
"F you end up running into this, there is a fix, it just isn't in the script as of this moment. **You have to create a new wait() time for 1 second**, and replace the wait() that comes after decodeSkill() to 1 second instead of .3 seconds."

**Comment by Zaein** [comment] 2018-12-27 03:10
I can't find decodeSkill() in either the FGO_EN_REGULAR.lua file or the regular.lua file

**Comment by TryBane** [comment] 2018-12-27 03:12
XD It is in the autoskill.lua file which is in the modules folder.

**Comment by TryBane** [comment] 2018-12-27 03:20
You replace [this](https://github.com/29988122/Fate-Grand-Order_Lua/blob/c3d071147664a477e46f5b7831dfa91055ab0e49/modules/autoskill.lua#L150)lines wait time and before decodeSkill you make the new wait time as 1 second

**Comment by Zaein** [comment] 2018-12-27 04:44
I replaced the wait times. The script now looks like this:

                                 wait(1)
decodeSkill(command)
				wait(1)

Also tried this (incase it was in milliseconds):

                                wait(1000)
decodeSkill(command)
				wait(1000)



The good news is that the script is running, the bad news being its not doing anything lol.
I tried with and without autoskill as well. I am using the trial version of AnkuLua and the newest version of the script. I am running AnkuLua through the accessibility options.

**Comment by Zaein** [comment] 2018-12-27 04:51
Also, I have tried starting the script from the menu and from combat.

**Comment by TryBane** [comment] 2018-12-27 08:13
Where are you downloading the script from?
If you were downloading it from Release, there was a bug in it where Autoskill was not working as intended.
If you downloaded one of the pull requests, there is a good chance that was the reason as there was a bug in that too.

Otherwise, I'd have to look further into the problem. Give me these answers so I can know the problem. Also, if you downloaded from Release or a Pull request, those have been fixed (assuming it was the top pull request)

**Comment by Zaein** [comment] 2018-12-27 08:19
Hey TryBane,

I downloaded the latest one you posted here: https://github.com/29988122/Fate-Grand-Order_Lua/releases

It had been posted for 4 hours prior to be downloading it.

Just to make sure everything is being done correctly, I download the file and extract it to my desktop. I copy the folder and but it on my SDCard on my phone. I then load the script in AnkuLua. I get into a battle on fgo and I run the script.

**Comment by Zaein** [comment] 2018-12-27 08:34
Sure thing, I'll go ahead and do that now.

**Comment by Zaein** [comment] 2018-12-27 09:04
Still no go. I added some screenshots so that you can see exactly what I did with the programming. Also, some images of opening AnkuLua and running it during an FGO battle.

![fgolua2](https://user-images.githubusercontent.com/46139598/50473794-6b31ad80-098c-11e9-8a52-e1bac79eca2e.png)
![fgolua1](https://user-images.githubusercontent.com/46139598/50473795-6b31ad80-098c-11e9-8864-7422275bc360.png)
![fgolua3](https://user-images.githubusercontent.com/46139598/50473796-6b31ad80-098c-11e9-98f0-13b94f743676.png)
![fgolua4](https://user-images.githubusercontent.com/46139598/50473797-6bca4400-098c-11e9-9a45-466c7e5dab7a.jpg)
![fgolua5](https://user-images.githubusercontent.com/46139598/50473798-6bca4400-098c-11e9-8613-8f0b5e97c0ab.jpg)
![fgolua3](https://user-images.githubusercontent.com/46139598/50473799-6bca4400-098c-11e9-81e1-678e1eb05b18.jpg)

**Comment by TryBane** [comment] 2018-12-27 15:56
Yeah, do you see how you have bars on the left and right of the battle screen in the game? Those are the bars I was talking about. You have an aspect ratio that is NOT 16:9 which is the only aspect ratio currently supported. I've made a potential fix which I am looking to have people test if you want to try it.

Download [this](https://github.com/TryBane/Fate-Grand-Order_Lua/tree/TryBane-Resolution-Scaling) one and give it a try. You'll have to make the same changes again though.

**Comment by TryBane** [comment] 2018-12-27 15:57
Also, be sure to leave feedback on how it works in the pull request [here](https://github.com/29988122/Fate-Grand-Order_Lua/pull/148)!

**Comment by Zaein** [comment] 2018-12-28 00:00
Hey TryBane, thanks for still giving me help.
 
The new version didn't work as the script still isn't clicking the abilities HOWEVER for what it's worth I tried running the friend Gacha and I did notice it was clicking. It was just clicking below the button. I have attached a picture to help you out. The red circle is where the script is clicking.

I'll put my feedback in the other thread as well and include the picture.
![screenshot_20181227-185612](https://user-images.githubusercontent.com/46139598/50497865-b2aa4f00-0a09-11e9-9955-74177a319fba.jpg)

**Comment by TryBane** [comment] 2018-12-28 00:03
You said it wasn't clicking the abilities, but was it at least clicking to start quest and such?

Also, the friendpoint gacha wouldn't click in the right place because the screen resolution scaling isn't applied to it.

**Comment by Zaein** [comment] 2018-12-28 00:11
I tried from the quest selection menu and it DOES click the quest. However, it won't click a support servant and it won't battle with AutoSkill ON or Off

**Comment by TryBane** [comment] 2018-12-28 00:11
Also, I just made an update that will allow for some slightly easier methods of debugging. After you download it, go into FGO_EN_REGULAR.lua and scroll to the very bottom. You'll see a variable there called "DebugMode" and it is set to "false". Go ahead and change that to "true" (no quotes) and take a screenshot of each time the screen is flashed with a red square.

Also, make sure the wait times are not 1000, it is not in milliseconds, they are in seconds.

**Comment by Zaein** [comment] 2018-12-28 00:14
Alright, I'll look to dl it in like 10 mins

**Comment by TryBane** [comment] 2018-12-28 00:15
I just modified it, feel free to download it now.

**Comment by Zaein** [comment] 2018-12-28 00:49
Yeah, I just used the last link np. It just takes me a while to set everything up and take the pictures. Each time I double-check to make sure I didn't fuck something up on my end.

In like ~150 there is an end ) missing from the wait command. This is in the autoSkill.lua file.

I have attached pictures and the red squares are the location the debugging thing is popping up at.
![screenshot_20181227-193957](https://user-images.githubusercontent.com/46139598/50498637-8ba34b80-0a10-11e9-94c5-67c390bc719f.jpg)
![Uploading Screenshot_20181227-194020.jpg…]()
![Uploading Screenshot_20181227-194450.jpg…]()

**Comment by TryBane** [comment] 2018-12-28 00:50
I was hoping to have the red squares that actually pop up XD

**Comment by Zaein** [comment] 2018-12-28 00:51
They pop up and immediately disappear so its hard to get a shot of them

**Comment by TryBane** [comment] 2018-12-28 00:55
Hmmm I could've sworn I set it so they'd be up for half a second. I thought that would be enough time.

I'll make 1 more debug change it'll take just a second.

**Comment by TryBane** [comment] 2018-12-28 00:58
Alright changes made. Now they should stay up for 2 seconds. Also, from the main menu, it should send a message saying what the x and y offsets are. Please remember those and post them in here for me.

**Comment by Zaein** [comment] 2018-12-28 01:34
I'll go ahead and take care of this. This time these pictures will be exactly what you want haha. Ill record the x and y offsets as well.

**Comment by Zaein** [comment] 2018-12-28 01:59
No luck. There are no messages appearing that tell me the x, y coords. There is also not a debug box during the battle menu like previously. It is still selecting the mission just fine.

In the autoSkill.lua there is still a ) missing in the wait command on like 148 above the decodeSkill. This isn't an issue for me as I am changing the wait times anyways but to anyone else trying to test your script they will get an error saying that a ) and may not know how to fix it themselves.
![screenshot_20181227-204417_fate_go](https://user-images.githubusercontent.com/46139598/50499766-56036000-0a1a-11e9-9c7f-9ceaa6bc3e68.jpg)

**Comment by TryBane** [comment] 2018-12-28 02:18
Ah, my bad. One sec and I'll solve that. Also, the x and y offsets should be shown when you're at the Main Menu.

**Comment by Zaein** [comment] 2018-12-28 03:46
Okay, I'll try it out and post the results.

**Comment by Zaein** [comment] 2018-12-28 04:02
Still no coords and no red boxes during battle. It behaves the same it did previously.

**Comment by TryBane** [comment] 2018-12-28 04:03
You made sure to set debug to true first right?

**Comment by Zaein** [comment] 2018-12-28 05:12
I didn't have it on! I apologize for that. I did it again and have attached the images! Coords didn't pop up for everything btw.

![screenshot_20181228-000802_fate_go](https://user-images.githubusercontent.com/46139598/50503458-29a90d00-0a35-11e9-8560-66307fc1a63d.jpg)
![screenshot_20181228-000856_fate_go](https://user-images.githubusercontent.com/46139598/50503459-29a90d00-0a35-11e9-9f3f-d080eade59bf.jpg)
![screenshot_20181228-000859_fate_go](https://user-images.githubusercontent.com/46139598/50503460-29a90d00-0a35-11e9-9ce5-5d42d62e2987.jpg)
![screenshot_20181228-000910_fate_go](https://user-images.githubusercontent.com/46139598/50503461-29a90d00-0a35-11e9-8357-3b99d6f20f38.jpg)
![screenshot_20181228-000643_fate_go](https://user-images.githubusercontent.com/46139598/50503462-29a90d00-0a35-11e9-9204-eb1d081dc608.jpg)

**Comment by TryBane** [comment] 2018-12-28 05:36
You're good man. The results are interesting, didn't expect that. I'll take a look at the script to see if I can figure out what is going wrong there.


As for the coordinates, it is only providing the offset, which is the same throughout the lifespan of the script so I only need it popping up once.

**Comment by TryBane** [comment] 2018-12-28 05:42
Alrighty, I've made an adjustment. See if that fixes it if you would.

**Comment by Zaein** [comment] 2018-12-28 05:58
I'm checking now!

**Comment by TryBane** [comment] 2018-12-28 06:00
If it doesn't work, I'll make another adjustment to try to debug. But firstly post a new set of screenshots if that is the case so I can have an idea of what changed.

**Comment by TryBane** [comment] 2018-12-28 06:07
I think it isn't going to work based on the offset it posted for x. I am going to make an adjustment to learn the resolution that Ankulua reads your device as in preparation for it not working. I will edit this when I make the adjustment.

**Comment by TryBane** [comment] 2018-12-28 06:14
Alright, I've made an adjustment for debugging. If it doesn't work, post the screenshots here and try downloading the version I just commited and post a screenshot of the values it posts while DebugMode is true.

**Comment by TryBane** [comment] 2018-12-28 06:44
When you snag the new one, you only need to take the screenshot of the message that pops up when you first set it up. It'll say the resolution.

**Comment by Zaein** [comment] 2018-12-29 00:45
Here is the picture with the resolution.
![screenshot_20181228-194210_fate_go](https://user-images.githubusercontent.com/46139598/50531513-26675d00-0ad9-11e9-97de-31068b95268c.jpg)

**Comment by Zaein** [comment] 2018-12-29 00:46
If you need something else just lmk

**Comment by TryBane** [comment] 2018-12-29 00:56
Hmmmm, interesting. I'm going to give a try. I don't know if it'll work but we shall see!

**Comment by TryBane** [comment] 2018-12-29 00:58
Alright. I've made a change. Go ahead and redownload the solution and try it without the debug. Let us see if it works!

**Comment by Zaein** [comment] 2018-12-29 02:59
Okay, checking it out now with the debug off!

**Comment by Zaein** [comment] 2018-12-29 03:11
Great news TryBane! It's working! Now, I haven't done it with autoskill enabled yet but I am about to. I just need to run an errand real quick.

I went from the battle menu to combat and back to selecting the same mission again. Once again this wasn't with autoSkill and I'm not sure if it is finding the correct support servant but PROGRESS IS PROGRESS! POGCHAMP!

**Comment by Zaein** [comment] 2018-12-29 03:50
Autoskill is mostly working, it just gets hung up sometimes because its clicking on the skill and holding which causes a window to pop up. Is this something that I can just change on my end? I'm thinking if I mess with those Autoskill timers I could probably solve this. 

It is correctly picking supports! Wonderful! Woo, we're almost there!!

**Comment by Zaein** [comment] 2018-12-29 05:08
Continuing with where I left off, I have changed to use confirm skills and the skill menu is working just fine until it gets to use a NP. I can't get the script to click the NP, it clicks and holds and that just brings up details of what the NP does.

When I use the manual support setting the script isn't suppose to turn off, is it? It doesn't continue running after I manually select a support.

**Comment by Zaein** [comment] 2018-12-29 10:06
TryBane, 

I think the script is trying to scroll down but it isn't successfully doing so and is instead selecting a servant. This could be an issue that is similar to the other resolution ones, know? Another thing that is happening is after it accidentally clicks a servant it gets stuck in the next window where you select the "Start Quest" button.

I have tested autoSkill and the autoSkill_list options and they are doing great! I can auto the battles just fine now!!

Thanks for your helping man! We have come a long way for sure!

**Comment by TryBane** [comment] 2018-12-29 11:33
Okay, so I don't actually have a very good solution to this as of yet. The softfix that my buddy had come up with was to use NO swipes and just refresh a boatload of times. Until I can come up with a solution, which you can help with if you want, then you can use that until then. Otherwise it might be a bit.

**Comment by Zaein** [comment] 2018-12-29 12:20
I have been running it for the last two hours or so. Occasionally, it will choose a Waver from my support list like it should. I think it is doing it fine if wave is in one of the first 3 slots on the friend list because then the script doesn't have to scroll.

**Comment by Zaein** [comment] 2018-12-29 15:51
The solution you proposed works! It is a nice little band aid. Now the script runs continuously, it can just take a long time to find the right servant at times.

If you need someone to test solutions to this just lmk and Ill be here to help!

**Comment by TryBane** [comment] 2018-12-29 16:14
I appreciate it! After a bit of testing, I do NOT believe it is a problem with using accessibility or your device. I believe it is actually the Android version (as accessibility can be used on earlier versions which I tested on my own device). This helps I think because it makes it so that we only need to propose this band-aid for those with 8.0 and above until a better solutions comes into play. I appreciate the support! I'll let you know when I've created an update that may or may not fix the problem.

**Comment by 29988122** [comment] 2018-12-30 12:08
@Zaein 

The aforementioned simple guide for same account on different machine:
https://github.com/29988122/Fate-Grand-Order_Lua/wiki/Same-account-on-different-phones-and-emus-at-the-same-time

**Comment by potchy** [comment] 2019-01-05 18:30
> The only issue I am having now is using the preferred servant option. After selecting the quest , in the second menu where you choose the support servant, I think the script is trying to scroll down but it isn't successfully doing so and is instead selecting a servant. This could be an issue that is similar to the other resolution ones, no? Another thing that is happening is after it accidentally clicks a servant it gets stuck in the next window where you select the "Start Quest" button.

This also happened to me on my new device. Commit 373f76c8b4e4f6a8052157686e89ac162cb76aed should fixed it.
I'm not sure why though. I just tried different parameters when calling `setManualTouchParameter()`.

**Comment by ryuga93** [comment] 2019-01-06 09:35
@potchy 
Weird, I tested on Nox with 2688x1242, 2246x1080, 2388x1668 and all are working fine with the original parameters of 1. Using Ankulua 8.1.1 with default settings.

The only time it did not scroll was using 1440x900, where it just did nothing for some time and proceed to update the support list.

**Comment by TryBane** [comment] 2019-01-06 09:47
I am fairly sure that the issue doesn't stem due to aspect ratio but based on android version. Though I may be completely wrong. I can actually test this soon though.

**Comment by potchy** [comment] 2019-01-06 13:35
@ryuga93 it's working fine on Nox. I'm certain the aspect ratio has nothing to do with it. I'm just not sure if the cause is the Android version or the Accessibility mode. My phone is unrooted, so I can't test AnkuLua in Daemon mode, at least not in 8.0.

**Comment by ryuga93** [comment] 2019-01-06 14:19
So we'll have to wait for @TryBane to test it.

**Comment by TryBane** [comment] 2019-01-06 16:20
If someone else is able to test it, that'll be good. When I said "Soon" I was referring to when I get my new phone. Which won't be for at least a week, if not 2 weeks. Kinda broke the screen on my current one so upgrading to an S9+. Luckily, it wasn't my FGO phone! (I had two S7s) So I can still play, but I can test accessibility mode when I get the S9+.

Just going to be a week before I order it due to financial reasons.

**Comment by TryBane** [comment] 2019-01-06 17:57
Check out the pull request #154 there, he made the change there that we need to test. Keep in mind that notches are still not supported (can't recall who had that issue)

**Comment by Zaein** [comment] 2019-01-06 18:07
What are notches?

**Comment by TryBane** [comment] 2019-01-06 18:15
If you don't know then your device doesn't have one :D 

Simply put, it's when there is a front camera that is within the screenspace itself or something to that affect, which affects the screenspace that the app takes up. Considering the aspect ratio issue normally deploys equal width on the bars on either side, the notch actually displaces those bars unevenly making our aspect ratio fix not work with them. We are working to fix it, but that is what I meant when I said it isn't supported yet.

But if you don't know what they are, then you don't need to worry about them. Feel free to test the pull request I posted above and see if preferred support selection actually scrolls through servants! If it does, then awesome. If not, we gotta try a different fix method.

**Comment by Zaein** [comment] 2019-01-06 18:51
Haha, sounds good. I'll go ahead and test it now. Could this also fix the friend gacha script, too?

**Comment by TryBane** [comment] 2019-01-06 18:58
No, this will not fix the friend gacha script. I can apply a fix for that later. along with the lotto box script.

**Comment by Zaein** [comment] 2019-01-06 19:06
Its scrolling and selecting the proper servant AND CE! Woo! I'll monitor it and make sure it can continue to do it but its look good!

You guys are the shit!

**Comment by TryBane** [comment] 2019-01-06 19:11
AWESOME! Good to hear. After everything gets approved and merged, I'll make a small commit to fix the friend gacha and lotto box. It is a small change so it won't take long. Just want to wait till after the merge to prevent any conflicts.

**Closed** 2019-01-14 14:49 UTC
Labels: bug
