### ISSUE TITLE
Still select stunned skill

### ISSUE THREAD

**Issue by Abdallah198UX** [29988122/Fate-Grand-Order_Lua#388] opened 2020-06-06 13:13 UTC
Find a way to avoid this.

**Comment by reconman** [comment] 2020-07-04 15:48
So what would be your proposed solution?

If you rely on a stunned skill in your 3 or 4 turn setup, it usually means that the setup will be broken and the script cannot fight as planned.

**Comment by reconman** [comment] 2020-08-12 20:31
Duplicate of #91

**Closed by reconman** 2020-08-12 20:31 UTC
