### ISSUE TITLE
Runtime error:

### ISSUE THREAD

**Issue by I8R4H1M** [29988122/Fate-Grand-Order_Lua#248] opened 2019-09-07 10:00 UTC
![Screenshot_20190906-142305](https://user-images.githubusercontent.com/16815544/64473432-54895a80-d199-11e9-9d8a-7b5c89249a07.png)
 how to solve this problem? It just stop at this point

**Comment by mdasavage** [comment] 2019-09-07 11:16
AnkuLua will ask you to allow it to do various things on your android device. One of them is accessibility  options, with the AnkuLua the ability to input touch and swipe commands I believe. Did you give AnkuLua all possible permissions? Just a guess. It works fine for me and I'm on android 8.0.

**Comment by docperian** [comment] 2019-09-07 16:42
![image](https://user-images.githubusercontent.com/13664849/64477691-aff12380-d16c-11e9-8ba1-226252f10289.png)
I gave Ankulua all permissions. I am using the latest version of nox and using android 7.

**Comment by I8R4H1M** [comment] 2019-09-07 23:58
I gave ankulua all possible permissions, and I'm on Android 7.0. everything works, just that the script won't scroll down to find the specific support servants. I'm not sure what to do

**Comment by yassoo1212** [comment] 2019-09-17 01:27
i was  farming nicely these 2 days, until my phone suddenly restarted earlier, and i read that i have to reinstall daemon when phone restarts,
anyway, now i have that error, i launch the script nothing happens then runtime error

**Comment by TryBane** [comment] 2019-09-17 11:42
For everyone having this issue, try restarting your phone (again if it already restarted), reinstall Daemon BEFORE opening Ankulua on your phone. Wait for it to say you can close it, then open Ankulua on your phone. Then give this a try again. If it fails again, repost here with what the issue is, otherwise please state if it solved the issue.

**Comment by yassoo1212** [comment] 2019-09-19 15:22
solved

**Closed** 2020-03-21 00:46 UTC
