### ISSUE TITLE
[Issue] First skill not activating?

### ISSUE THREAD

**Issue by TryBane** [29988122/Fate-Grand-Order_Lua#47] opened 2018-07-16 11:23 UTC
Alright so for some reason when using skill confirmation off the first skill in the list doesn't activate. I've made a work around for this by doubling the first skill so it activates, but not sure what the reason is for it. I've poured over the code looking for what the issue is and still haven't found it. Maybe those more familiar with the code might have better luck.

As for me, I had this before - Skill_Command = "hi5,#,x21g25,#,4"
Now I have this - Skill_Command = "hhi5,#,x21g25,#,4"

The second one works like the first one should. First skill is activated on the first turn, then the second skill, then a noble phantasm. I didn't have any issues with the following stages activating skills (though there seems to be some weird behavior with the NPs in stage 3 I believe?)

**Comment by potchy** [comment] 2018-07-16 22:31
Do you see the actual click being made?

I've encountered this issue before and it was because the click was being made before the icons were on-screen.

**Comment by TryBane** [comment] 2018-07-17 01:03
I'm not entirely sure. I'm pretty sure the labels for the battle come up first doesn't it? Cause that definitely comes up first. You may be right in needing to extend the wait time for the skill activation.

**Comment by 29988122** [comment] 2018-07-19 15:53
Yeah, glad that you solved it. 

Sometimes it's not quite ideal to have longer wait() as base code cause..you know, lots of our user use emulator and it's enough for most of the machines. 
I've already slow it down myself for like 3 times in the last 6 months, xD.

**Comment by TryBane** [comment] 2018-07-22 21:43
Okay, so this issue was closed cause I got it working but the issue is happening again. This time, it can't be the wait. 2 reason why that is.

Firstly, I extended the wait... a lot. Increased the wait before executeskill() to 4.5. Then when that still wasn't working I thought maybe it's the wrong wait? Went to the previous one and upped that by 3 seconds. Still didn't work.

Secondly, I tried something different. I tried starting it while in the first battle screen. If the issue was the wait time, then that shouldn't come up when it starts in the first screen. But it did.

I don't know what's going on, it's unexpected behavior which means it's probably an issue with memory.

**Comment by 29988122** [comment] 2018-08-11 11:38
I'm cleaning the code, and I guess it's somehow related in the function decodeSkill(str, isFirstSkill).

If it's not an array reading/modifying/writing issue, then I bet it's here.
But I can't quite recreate the issue, so I guess soon^tm

**Comment by 29988122** [comment] 2018-08-17 06:26
Hey I think I can now recreate the bug:

Assume skill_command = "abcde"

Then it will cast only bcde in the first stage/first turn of battle.
It has to be "abcde,#,#" so the script will cast skill a.

@ryuga93 
If you have time, can you take a look at it? 
I don't really have the "level" to understand the skill parser. QQ for me.

Thanks!

**Comment by ryuga93** [comment] 2018-08-17 08:50
Sure, but no ETA :( 
Did it occur only in the first stage/first turn?

**Comment by 29988122** [comment] 2018-08-17 09:10
Not sure, can't test now thanks to Windows Update.

But I believed it only occurred in the first stage/turn, since my experience stayed the same as @TryBane.

**Comment by 29988122** [comment] 2018-08-17 09:29
Another behavior detail.

"abc,#,#" will still trigger the bug, while "abc,#,0,#,0" will not.

**Comment by ryuga93** [comment] 2018-08-17 14:18
Hmm, I tried all of the commands "abc,#,#" "abcde" "hi5,#,x21g25,#,4"
The first skill can still be clicked, but I tried with the skill "g"and it clicked at the wrong place.
I'm using Nox though, were these commands tested on Nox?

**Comment by 29988122** [comment] 2018-08-17 14:48
I was test it on Nox personally, so yeah it's the command g that's not working.

But in @TryBane 's case, it's h.

**Comment by ryuga93** [comment] 2018-08-17 14:54
I'll solve this issue first, but for @TryBane the g can be click if repeated the second time, seems like a different bug to me.

**Comment by 29988122** [comment] 2018-08-18 08:03
I can't really recreate this situation. 
Tried clicking at different moment, different cpu loading, but the game still can register my click.

**Comment by ryuga93** [comment] 2018-08-18 10:26
Not sure what happened last night with Nox or the game, but now the autoskill function is running fine at my end. I can confirm it's not a problem with the script. 

Probably the game did not registered the first click, it happened to me before when I tried to make the auto support, where the click did not registered at the mid point of the confirm button when refreshing.

**Comment by 29988122** [comment] 2018-08-18 11:14
Could also be the issue from emulation, emu, or even Ankulua. Weird things happen all the time.

Can confirm I'm unable to recreate the issue now. 
Seems random as your test result.


What should we do (as coders do in real^tm development team) now?
Tag it as wontfix or low priority and call it a day? 

Not so familiar with real world development.

**Comment by ryuga93** [comment] 2018-08-19 05:37
I think would be appropriate to tag as wont fix and have a PSA for it

**Closed** 2018-08-19 09:01 UTC
Labels: bug, wontfix
