### ISSUE TITLE
Failed to determine card-type

### ISSUE THREAD

**Issue by GuinevereSnow** [29988122/Fate-Grand-Order_Lua#204] opened 2019-08-06 15:16 UTC
Android 5.1

Goes to battle 1/3 this thing pops out then it stucks
Any way to solve it?

![67578371_1132299010491381_7316081153528561664_n](https://user-images.githubusercontent.com/53827058/62552425-d862c680-b82a-11e9-8c4d-3754a97d98a8.jpg)

**Comment by TryBane** [comment] 2019-08-11 15:24
Can you post a full screenshot? Sorry for the delayed response.

**Comment by AdityaTeguh** [comment] 2019-08-13 07:03
i got the same problem

**Comment by Rajvir8** [comment] 2019-08-30 12:20
That generally pops up only if you messed up with autoskill, for example you ask it to click a skill on cool down or it's a skill that needs to be applied to somebody.  

Chances are they messed up on the skills section, and it automatically gave up that turn and just clicked the face cards to finish the turn.

**Comment by TryBane** [comment] 2019-08-30 12:49
That toast specifically comes up due to not being able to recognize the card type.

The code is present within the card.lua module and the process essentially is checking each card to see which one is which (quick, buster, arts, weak, resistant). And in the case where the card type isn't determined (doesn't match the Buster, arts, quick image) it pops up with that toast.

This occurs from numerous ways. Some of them include them being unable to act due to a stun/charm, cards already clicked, or if you click all the NPs. In the last case, the game exits the menu before the card types can be determined, thus since it can't label each card it comes up with that toast.

Essentially, I needed a full screenshot rather than the one he sent so that I could make a determination of if it was one of these problems specifically or if it was something that we haven't accounted for. But I can't help if there isn't a back and forth.

**Comment by zambospam** [comment] 2019-08-31 17:22
I'm not OP but since I'm experiencing the same issue I'll provide some screenshot I managed to take
![BlueStacks_2019 08 31_19 14 26 55](https://user-images.githubusercontent.com/33596528/64067167-842de500-cc24-11e9-898f-68a585eaa677.jpg)
![BlueStacks_2019 08 31_19 14 27 25](https://user-images.githubusercontent.com/33596528/64067168-842de500-cc24-11e9-899e-1575065aee4f.jpg)
![BlueStacks_2019 08 31_19 14 29 18](https://user-images.githubusercontent.com/33596528/64067169-842de500-cc24-11e9-8aaf-56833643e4d3.jpg)

I coudn't take a screen at the actual card selection because the script for me will autoselect the first three cards while issuing the errors

**Comment by TryBane** [comment] 2019-09-01 01:26
Alrighty. I see black bars, do you have a device with a notch?

**Comment by zambospam** [comment] 2019-09-01 09:19
I'm actually playing on a Bluestacks emulator.
I would also like to specify everything seems to work fine until that point:
it selects the right mission, use the selected stamina refill if necessary (I chose Golden Apples), chooses the specified support with the specified CE and uses the specified Autoskill.
Also, same as OP, the script kinda lingers there in idle after "Failed to determine" error..

**Comment by TryBane** [comment] 2019-09-01 09:35
Hmmm, odd. I'll check some things out when I get home to see if I can figure something out.

**Comment by TryBane** [comment] 2019-09-01 10:20
Okay, I've tried to take a look and it isn't being pleasant. So, do me a favor and get a screenshot of a set of cards where you have Arts, Quick, AND Buster, without the use of the script, and send that to me (with none selected)

I need to see if giving you an image of each card type ripped from your own screenshot will solve the issue.

**Comment by zambospam** [comment] 2019-09-01 10:38
Here you go
![BlueStacks_2019 09 01_12 38 40 05](https://user-images.githubusercontent.com/33596528/64075193-6eb4cb80-ccb5-11e9-9dd6-f435de2750b3.jpg)

**Comment by TryBane** [comment] 2019-09-01 10:50
![quick png](https://user-images.githubusercontent.com/24114484/64075307-af482100-cc84-11e9-9aac-72d48a6e179d.png)
![art png](https://user-images.githubusercontent.com/24114484/64075308-af482100-cc84-11e9-9ceb-e30ac1594b32.png)
![buster png](https://user-images.githubusercontent.com/24114484/64075309-af482100-cc84-11e9-91ea-9d819f8bfd30.png)

Try putting these in your EN image folder and see if they work.

**Comment by zambospam** [comment] 2019-09-01 15:09
Okay I did replace the images in the folder on my emulator, but I'm encountering a couple of issues yet:

1. (I don't know if I should start another thread for this) Battle 1/3. Started the script on the menu, works fine until the first fight, select the cards without the infamous "Failed to determine" error, then then it lingers there without giving me any message box error.
Image here: 
![BlueStacks_2019 09 01_16 51 57 90](https://user-images.githubusercontent.com/33596528/64078432-e5b08b00-ccda-11e9-96df-bf0577a5ec42.jpg)

2. I restarted the script right after, completed battle 1/3, correctly selected the cards for turn 1 of Battle 2/3, but then it gave me the "Failed to determine" error again.
Image: 
![BlueStacks_2019 09 01_17 01 34 41](https://user-images.githubusercontent.com/33596528/64078450-30320780-ccdb-11e9-88ad-cd0d36089454.jpg)

**Comment by TryBane** [comment] 2019-09-01 16:14
Okay, is there a way to change the inner resolution of Bluestacks? Right now the issue is that it is creating a funky resolution which is causing the card images to be inconsistent in their matching. Which is why it is working sometimes and sometimes not. I know that it's fairly easy to change resolution of the device you're emulating in Nox, but I haven't tried Bluestacks in over 3 years so I have no idea how that works.

**Comment by zambospam** [comment] 2019-09-01 18:05
I can also try to run it with Nox, what resolution should I use?

**Comment by TryBane** [comment] 2019-09-01 18:15
You can use any really. Not a specific one. The issue is that the resolution being used by bluestacks is uneven or something. So you can use 1280x720, 2560x1440. Stick with a typical and you won't have any issues.

**Comment by zambospam** [comment] 2019-09-01 18:46
I'm back after some tries with Nox (1280x720)

Selecting the mission, refilling stamina, choosing Friend Servant -> all good
the script went stuck at the very beginning of the battle, it didn't do anything at all:
![Screenshot_2019-09-01-20-35-20](https://user-images.githubusercontent.com/33596528/64080879-33d48700-ccf9-11e9-943e-f071897a0025.png)

I restarted it and I was given again the "Failed to determine" error again:
![Screenshot_2019-09-01-20-35-44](https://user-images.githubusercontent.com/33596528/64080888-549cdc80-ccf9-11e9-9257-d457fd47766c.png)
![Screenshot_2019-09-01-20-35-47](https://user-images.githubusercontent.com/33596528/64080890-58306380-ccf9-11e9-8f28-3154260eba72.png)
but this time it didn't idle right after but kept fighting (with Bluestacks it got stuck everytime after this error)

Unfortunatly the script froze again here: 
![Screenshot_2019-09-01-20-37-05](https://user-images.githubusercontent.com/33596528/64080905-9463c400-ccf9-11e9-8f7a-e947f515df05.png)
and here:
![Screenshot_2019-09-01-20-39-57](https://user-images.githubusercontent.com/33596528/64080907-9a59a500-ccf9-11e9-8be9-e3c345e8f1e4.png)

**Comment by TryBane** [comment] 2019-09-01 18:51
What version of Ankulua are you using? This is giving me nightmare flashbacks of #219 
All it took to fix the idle issue was updating Ankulua. However, regarding the "Failed to determine Card Type", don't forget to use the versions of the cards that are currently present in the script, not the ones I posted earlier.

**Comment by zambospam** [comment] 2019-09-02 09:11
On Bluestacks I had to use 8.3.0 because the newer versions weren't working.. On Nox I'll admit I used the same apk I used with Bluestacks.. I'll try to use the last version and see how it turns out

**Comment by TryBane** [comment] 2019-09-02 09:23
I have a strong suspicion is will work just fine once you update.

**Comment by zambospam** [comment] 2019-09-02 18:49
after some testing the issues seem to have disappear updating AnkuLua. Too bad I am forced to use Nox now, Bluestacks was more performing..

I have found another issue:
even though I have set Battle_NoblePhantasm to "danger", whenever I'm entering Battle 3/3 (against 3 Servants) the NP doesn't get chosen the first turn, here some proof:
![Screenshot_2019-09-02-20-01-29](https://user-images.githubusercontent.com/33596528/64130511-0b18c400-cdc3-11e9-85b1-78f76f59253a.png)
![Screenshot_2019-09-02-19-55-58](https://user-images.githubusercontent.com/33596528/64130512-0eac4b00-cdc3-11e9-859b-3f34f544be12.png)
I noticed I could have taken better screenshots but you can see that in turn 7 NP of 3rd servant is full yet the script chooses "standard" cards

**Comment by TryBane** [comment] 2019-09-02 19:52
That could be a result of the autoskill commands not being finished. The script won't use NPs when the "danger" option is chosen if Autoskill still has commands to be used. That changes on a turn by turn. So if the Skills are being cast on a turn, it reads that it isn't finished. And it does suck if bluestacks was faster.

**Comment by Sabersirius** [comment] 2019-09-27 11:01
Hello, I have the same problem. In my script Helena uses all her skills and Punyan uses her first skill, then still in Battle 1/3 Helena uses her NP. In Battle 2/3, Punyan uses her NP. Finally, in Battle 3/3, Chacha should use her NP... But happens this problem in the print, so the script can't use NP in Battle 3/3, the problem of @zambospam
![Screenshot_20190927-073929_-](https://user-images.githubusercontent.com/55816636/65764838-eaf7ce80-e0fc-11e9-9e3f-5c7a5fc2f9da.jpg)

Battle 1/3 and Battle 2/3 work perfectly ...

**Comment by TryBane** [comment] 2019-09-29 21:44
@Sabersirius Try using Ankulua 8.0 and give it another try.

**Comment by reconman** [comment] 2020-08-12 20:31
Closing because of no reaction from the author of the issue

**Closed by reconman** 2020-08-12 20:31 UTC
Labels: waiting for user reply
