### ISSUE TITLE
When skill command needs to use order change it misses the buttons

### ISSUE THREAD

**Issue by JustSomeone555** [29988122/Fate-Grand-Order_Lua#320] opened 2020-01-16 22:29 UTC
So when my game reaches the point where it should use order change to replace - 31 it clicks just above the buttons thus skipping the entire thing, also noticed it does that part particularly faster than the rest

Is there a way to slow that action down a notch and get it to pressing the buttons correctly?

**Comment by chairmanxyz** [comment] 2020-01-17 05:24
This seems to be caused by game lag that is super prevelent on the NA version right now. The way around it is after you do a command switch, or a skill that randomizes the star weight, you just put the skill in twice. So if you wanted it to hit skill a after a command switch you just do "aa." The first one will miss but then it'll hit it again and register that time.

**Comment by JustSomeone555** [comment] 2020-01-17 09:56
I just tried  it, so far it seems to be a stable fix.. thanks!

**Comment by TheRealPlagiariser** [comment] 2020-01-17 20:09
Paste your entire chain skill that you wrote in the code, along with the servants in correct order ( with backline) . I'll check it out for you and test it on my end.

**Comment by reconman** [comment] 2020-03-20 23:34
Duplicate of #300

**Closed by reconman** 2020-03-20 23:34 UTC
Labels: duplicate
