### ISSUE TITLE
Auto skill ignores 3. wave commands, goes for face cards instead

### ISSUE THREAD

**Issue by miro3no** [29988122/Fate-Grand-Order_Lua#306] opened 2019-12-23 13:39 UTC
Hello everyone.
I am trying to automate the christmas farming, but the command line just ignores the 3. wave script and goes straight to attacking the final boss with face cards istead.
My line of commands I was trying to implement is "ce4,#,fgdjb1t14,#,a2i2hx31gi25"
I can kinda get it work, if I ommit the 2. # and put it in like this "ce4,#,fgdjb1t14,a2i2hx31gi25" however, if I have bad face card luck during wave 2 and they do not kill the second enemy, the script just unleashes everything ready for final wave on the remaining wave 2 enemy.
I did try to use script as "ce4,fgdjb1t14,#,a2i2hx31gi25" and it skipped the entire 2. turn command line for some reason.
I did try to use both newer and older version of Ankulua, but there was no change in behavior.
Any help would be appretiated.

**Comment by MatheusOPP** [comment] 2019-12-23 23:56
Try putting a number of commas and zeros before the # separators. I assume you're Arash'ing the first wave, so in this case, you could change your command from `ce4,#,fgdjb1t14,#,a2i2hx31gi25` to something like `ce4,#,fgdjb1t14,0,0,0,0,0,#,a2i2hx31gi25`.

An explanation: the `,` separates turns and the `#` separates battle stage/waves (if you finish a wave before all turn commands in it are done, it just skips to the next #). The zeros basically represent turn skips, that is, "only facecard this turn", which you'll want to do right after using the NP in wave two if you get bad facecards and can't kill in one turn. In this case, the "turn skips" will only happen until the second wave ends, in which case it'll skip to the next `#`. Because of that and the fact that you're probably killing it the next turn, you may not need that many zeros actually, but either way once you kill it, the 2/3 wave ends and it skips to the command after the `#` so it makes no difference. If you have a chance of failing to one-turn in wave 1, you should do the same there, but if you're one-turning it, no need.

**Comment by miro3no** [comment] 2019-12-24 06:54
Hey. Thanks for the advice. Unfortunately, it does not work for me, and my team still proceeds to facecard wave 3 even after trying to add 0s to both 1. and 2. wave of commands (respectively and together, neither does work).

**Comment by MatheusOPP** [comment] 2019-12-24 23:16
> 
> 
> Hey. Thanks for the advice. Unfortunately, it does not work for me, and my team still proceeds to facecard wave 3 even after trying to add 0s to both 1. and 2. wave of commands (respectively and together, neither does work).

Could you give me your current command string?

**Comment by miro3no** [comment] 2019-12-28 12:06
> 
> Could you give me your current command string?

Hey, sorry for the late reply. Even though the event is now, over, I would love to get it fixed for the future. The string I got through the event was "ce4,#,fgdjb1t14,a2i2hx31gi25". If I did not get 4-5 Merlin cards on turn 2, I was able to face-clear the survivng enemy and the script went on for wave 3.

I did try "ce4,#,fgdjb1t14,0,0,0,0,0,#,a2i2hx31gi25", "ce4,0,0,0,#,fgdjb1t14,#,a2i2hx31gi25" and "ce4,0,0,0,#,fgdjb1t14,0,0,0,0,0,#,a2i2hx31gi25", but as long as I had the 2. # there, wave 3 always went straight to facecards. It happens all the time, even with different setups, as long as I have # after the 2. string of commands :(

**Comment by TheRealPlagiariser** [comment] 2020-01-05 21:05
Sorry for bumping onto this issue, the "unleashing" of all battlephase 3 skills should not occur while still in battlephase 2 even if you have only specified the conditions for 1 turn while it actually took 2+ turns for phase 2. YOU DO NOT NEED TO ADD 0s IF YOU ARE DOING MORE THAN 1 TURN AND WANT TO FACE CARD. THE SCRIPT KNOWS TO FACECARD WHEN THERE IS NO SKILL IN THE ARRAY. Look at the code:

	if Enable_Autoskill == 1 then
		_autoskill.Execute()    
	end

	if not _hasClickedAttack then
		clickAttack()
	end

Just for the sake of reproducing this, I've fully tested a node where I had scathach fire up her quick buff in 2nd round and use her NP, while facecarding the remaining 2 mobs. 

Servants used in order : Artoria , Scathach(lancer), Frankenstein(berserker)
chain : "ab4,#,e25,#,i6"

Script automated:
BP1 Turn 1 : Artoria buff 1 ,buff 2 ,NP + Command Cards
BP2 Turn 2 : Scathach self buff 2 ,NP + Command Cards
BP2 Turn 3 : Command Cards
BP3 Turn 4 : Frankenstein buff 3 ,NP

Conclusion: Highly likely there's either a mistake on your setup formation/skill chain OR it could be the array went out of bounds from the numerous skills, unfortunately I don't have the time right now to test it fully for you with a full comp of buffers with plugs, but the case should come clear by DV.

**Comment by miro3no** [comment] 2020-01-07 13:32
Hey. Thanks for getting to my problem. I did a very simple test today.
Arash, Merlin, Spartacus + Backline KscopeFran
The chain is simply "ch4,#,d6,#,4"
The problem still presists. On wave 3, Fran does not use NP and team starts to attack with facecards instead. As soon as I remove the 2. # and put it like "ch4,#,d6,4" it works.
I can live with it on door farming and such, where there is no chance of not 3turning, but at something more complex, it can royaly screw me up if RNG goes wrong. (as it did at Christmas3)

**Comment by TheRealPlagiariser** [comment] 2020-01-07 13:35
Ok what version of ankulua are you using?

**Comment by miro3no** [comment] 2020-01-07 13:40
I am currently at 8.6. but the same thing was going on when attemted on the older ones.

**Comment by TheRealPlagiariser** [comment] 2020-01-07 14:03
I've tried the "ch4,#,d6,#,4" with arash,merlin,spartacus + backline kscope fran.

It's working just as expected.
W1 arash NP-> dies then fran comes
W2 spartacus NP
W3 fran NP

The problem must be on your end indeed, please record and upload the video

**Comment by miro3no** [comment] 2020-01-08 13:38
Hey. Sorry for the delay. My phone could not handle screen capture software properly and I did not have another capture device at hand yesterday. 

https://youtu.be/OBWHsuVUL-0

There is the video of my script running. Everyting goes fine untill wave 3.
During the recording I noticed, that the script changes the target (probably due to auto-targeting), but does not use NP (or skills, when I tried to add those into the script in different run) anyway.

**Comment by TheRealPlagiariser** [comment] 2020-01-08 13:58
Ok I used the script a few times now, never got that CAUTION warning about using autoskills. Try running the script in support menu please. See if that fixes the issue.
I've figured it's either that or it's because your phone is so slow that it's not registering the last phase.
If you have a decent PC and can use an emulator on it, please try testing on the emu.

**Comment by miro3no** [comment] 2020-01-08 15:16
Even though the script should have been latest version, I re-downloaded it just in case. Sadly, it did not help. When it comes to emulation, my PC is over 10 years old now... I can boot Nox, but it barely starts the app (with stable 1-2fps!) and Bluestacks straight out crashes my PC :D I may give it a shot when I get to my laptop, but I have that one in my student's house and will not go there for at least a week. When I test it there, I will give you an update, wether it works there or not.

**Comment by reconman** [comment] 2020-08-31 21:34
No reply from user for months, closing now.

**Closed by reconman** 2020-08-31 21:34 UTC
Labels: waiting for user reply
