### ISSUE TITLE
[Feature Request] Auto Support list

### ISSUE THREAD

**Issue by looowkeydude** [29988122/Fate-Grand-Order_Lua#258] opened 2019-09-13 14:37 UTC
Can we have auto support list like autoskill list? or merged with it? like for farming qp I like to use auto skill slot 1 w/ support with mlb monalisa but for event I use autoskill slot 2 w/ mlb event ce's

thanks

**Comment by potchy** [comment] 2019-09-14 23:18
I'm personally against it. The settings file would get too bloated as there are many parameters for support selection. Just make separate files.

**Comment by TryBane** [comment] 2019-09-17 11:57
I had made this modular before where you could select support and skill lists in similar ways at run time. But when I had friends give those a try, they complained that starting the script was a pain because you had to navigate so many menus to get it working. Thus, I never tried to pull it into the main. Best I think we could do is allow players to list CEs and Servants to be used in the config file and then allowing them to select which they want to use on that specific run.

**Comment by reconman** [comment] 2020-03-21 01:18
Duplicate of #101

**Closed by reconman** 2020-03-21 01:18 UTC
