### ISSUE TITLE
Script issues when playing on CN

### ISSUE THREAD

**Issue by Sabersirius** [29988122/Fate-Grand-Order_Lua#412] opened 2020-08-25 00:17 UTC
Playing on server CN, the script does not click 连续出击 (Repeat) and does not recognize the type of cards after the 4th anniversary update...
![Screenshot_2020-08-24-20-14-57-846_com bilibili fatego sharejoy](https://user-images.githubusercontent.com/55816636/91108211-bf070500-e64d-11ea-9016-cd8aded4d836.jpg)

**Comment by Sabersirius** [comment] 2020-08-27 16:18
Hello?

**Comment by reconman** [comment] 2020-08-27 18:16
Duplicate of#411, already fixed

**Closed by reconman** 2020-08-27 18:16 UTC
