### ISSUE TITLE
Script doesn't read last turn

### ISSUE THREAD

**Issue by Grublixx** [29988122/Fate-Grand-Order_Lua#166] opened 2019-02-06 20:14 UTC
Hi.
I'm trying to farm door with this setup "cl1defghi5,#,6,#,4". Everything works except the last turn. Whatever i put there, it doesn't execute and goes into auto mode. I still finish the quest, but i would like to know what wrong for the futur.

Thank you

**Comment by potchy** [comment] 2019-02-06 21:22
I couldn't reproduce your problem. That command list is working normally for me.
What server do you play in? EN, JP, TW?

**Comment by FireZura** [comment] 2019-02-06 21:45
EN. 
On a samsung galaxy S7, android 8.0 if that helps.

**Comment by FireZura** [comment] 2019-02-07 12:28
[FGO_EN_REGULAR.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2840775/FGO_EN_REGULAR.zip)

**Comment by potchy** [comment] 2019-02-07 18:29
Still can't reproduce. I'm farming Valentine's and it's working great.
#164 seems to have the same problem. Maybe one of you can share a video?

**Comment by FireZura** [comment] 2019-02-07 21:07
Sorry for the shit quality. The script makes the recorded video freeze with all the apps i tried, so i had to take it with my computer camera
[video](https://streamable.com/mfa1a)

**Comment by potchy** [comment] 2019-02-08 00:21
Get this file: [autoskill.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2843167/autoskill.zip)

Replace the one that already exists in the `/modules` folder. Start the script as normal.
A dialog like the one below will appear every turn. Every time it appears, take a screenshot and click OK to continue. Post all of them here when finished.

![screenshot_2019-02-07-22-15-22](https://user-images.githubusercontent.com/4316326/52451537-903a4400-2b26-11e9-8593-c27a5f4b7876.png)

**Comment by FireZura** [comment] 2019-02-08 05:28
![screenshot_20190208-062031_fate_go](https://user-images.githubusercontent.com/30664342/52460438-9baf5e80-2b6a-11e9-983d-389db4614be7.jpg)
![screenshot_20190208-062147_fate_go](https://user-images.githubusercontent.com/30664342/52460452-ab2ea780-2b6a-11e9-86d7-e56659e264dc.jpg)
![screenshot_20190208-062236_fate_go](https://user-images.githubusercontent.com/30664342/52460458-aec22e80-2b6a-11e9-9d9d-6cdaba1bd84c.jpg)
![screenshot_20190208-062310_fate_go](https://user-images.githubusercontent.com/30664342/52460463-b255b580-2b6a-11e9-8084-27a226e8a266.jpg)

**Comment by potchy** [comment] 2019-02-08 22:25
@29988122 
I think the script is not recognizing the stage changes. Any ideas? Q_Q

**Comment by 29988122** [comment] 2019-02-10 04:55
https://github.com/29988122/Fate-Grand-Order_Lua/blob/master/modules/battle.lua
```
Line 125
local currentStagePattern = Pattern(GeneralImagePath .. "_GeneratedStageCounterSnapshot.png"):similar(0.8)
```
The best we can get to solve @FireZura 's issue is similar 0.8 -> 0.85 or 0.9.

It indeed sometimes got it wrong, as the color of background's similar. (Waiting for Ankulua to implement transparent XD)
However, make the threshold higher would always make false-positive. (stage not changed, but script thought it changed)

Any idea?

**Comment by potchy** [comment] 2019-02-10 15:42
@FireZura 
Try to adjust the similarity % to 0.85 or 0.9, like @29988122 suggested. Tell us if it works.

**Comment by FireZura** [comment] 2019-02-10 16:51
Nope. I'll just remove the # between turn 2 and 3
But the script works for the event.

**Comment by potchy** [comment] 2019-02-10 23:01
Uh, nope what? You tried and it didn't work?

**Comment by FireZura** [comment] 2019-02-11 03:42
Yeah i tried with both 0,85 and 0,9 and got the same result
null

**Comment by 29988122** [comment] 2019-02-11 06:49
It's the exp farming stage, and on my side it worked flawlessly - not saying you're wrong or what, but this is indeed weird.

Does your Ankulua have storage permission? Could be snapshot access issue.

**Comment by FireZura** [comment] 2019-02-11 09:50
![screenshot_20190211-104531_ankulua](https://user-images.githubusercontent.com/30664342/52555691-b5f76f80-2dea-11e9-8387-3907bc357a68.jpg)
![screenshot_20190211-104502_package installer](https://user-images.githubusercontent.com/30664342/52555701-bd1e7d80-2dea-11e9-898b-f150784897ef.jpg)

**Comment by potchy** [comment] 2019-02-11 19:41
Hey, if you don't mind, try this: [debug.zip](https://github.com/29988122/Fate-Grand-Order_Lua/files/2852754/debug.zip)

Extract both folders to the same place your script is and overwrite everything that already exists.
Use the script to clear the same quest of that video you posted a few days before. Do this only once.
Now, there should be a few images in the `/image_debug` folder. Zip and post them here.
![screenshot_2019-02-11-17-39-52](https://user-images.githubusercontent.com/4316326/52588653-1b1b8700-2e24-11e9-9fe3-91a8517444ff.png)

**Comment by FireZura** [comment] 2019-02-13 09:31
![screenshot_20190213-102928_fate_go](https://user-images.githubusercontent.com/30664342/52701400-752e6080-2f7a-11e9-9e28-f1883d172150.jpg)

**Comment by potchy** [comment] 2019-02-13 16:31
You probably forgot to click the "start capture" button after running AnkuLua.

**Comment by FireZura** [comment] 2019-02-14 22:12
Euh... i don't see any start capture button. Do i need the pro version ? Could you show me where it is with a screenshot ?

**Comment by potchy** [comment] 2019-02-14 22:43
It's this one. 
Mine's in Portuguese. It says:
"AnkuLua will start capturing everything on screen.
Cancel - Start capture" 

![screenshot_2019-02-14-20-40-03-252_com android systemui](https://user-images.githubusercontent.com/4316326/52822498-faa83280-3098-11e9-869f-fe3d3b41613a.png)

**Comment by iamcurseal** [comment] 2019-07-08 09:19
I have the same problem too. I tried to use sir @potchy's debug.zip but i dont know where I can find the images. Sorry for bad english.

**Comment by TryBane** [comment] 2019-08-26 09:23
@29988122 Pretty sure they have Transparency implemented? Either that or I'm completely misunderstanding something here XD

https://sikulix-2014.readthedocs.io/en/latest/pattern.html#Pattern.Pattern

https://puu.sh/E9ElG/98b831f5c7.png

**Comment by TryBane** [comment] 2019-08-26 09:36
Just did this real quick using the "snapshop" that is in the JP folder on https://www.online-image-editor.com/ with the transparency wizard. Haven't tried it or anything, but utilizing this with the Pattern(""):mask("")

![Turn 3 (transparent)](https://user-images.githubusercontent.com/24114484/63680915-a4901680-c7c2-11e9-8e02-ca42aec16083.png)

I think I might test this with Turn 1 on JP as well and will report back on it.

**Comment by reconman** [comment] 2020-08-31 21:26
No reply from user, closing now. Also seems related to the stage counter similarity: https://github.com/29988122/Fate-Grand-Order_Lua/issues/382#issuecomment-629859967

**Closed by reconman** 2020-08-31 21:26 UTC
Labels: bug, waiting for user reply
