### ISSUE TITLE
Repeat quest screen

### ISSUE THREAD

**Issue by Hikaru9569** [29988122/Fate-Grand-Order_Lua#397] opened 2020-07-04 11:37 UTC
Because of the way the script is set up it cannot get past the repeat Quest screen and is unable to continue the loop running the quest
![Screenshot_20200704-043708_FateGO](https://user-images.githubusercontent.com/53490440/86511659-0d1b2d00-bdb0-11ea-8ea4-04ed18698cf7.jpg)

**Comment by reconman** [comment] 2020-07-04 11:39
Have you made sure to update your script files?

**Comment by reconman** [comment] 2020-07-04 11:40
Duplicate of #392

**Closed** 2020-07-11 13:02 UTC
